"""added availability column in car

Revision ID: 0d2d96b6f521
Revises: 69a338214283
Create Date: 2021-11-30 01:34:27.687765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d2d96b6f521'
down_revision = '69a338214283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('availability_for_60_days', postgresql.ARRAY(sa.Date()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'availability_for_60_days')
    # ### end Alembic commands ###
