"""added modified_on column

Revision ID: 69a338214283
Revises: c2164fb215a0
Create Date: 2021-11-29 22:19:49.290325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a338214283'
down_revision = 'c2164fb215a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('car_booking', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('city', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('rental_zone', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_zone', 'modified_on')
    op.drop_column('city', 'modified_on')
    op.drop_column('car_booking', 'modified_on')
    op.drop_column('car', 'modified_on')
    # ### end Alembic commands ###
