"""registration_no not null constraint

Revision ID: c2164fb215a0
Revises: fbad207f7e56
Create Date: 2021-11-28 09:48:28.569422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2164fb215a0'
down_revision = 'fbad207f7e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'registration_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'registration_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
