"""added unique constraint on rental_zone name

Revision ID: f0c96c0e7d16
Revises: 0d2d96b6f521
Create Date: 2021-11-30 03:45:39.671528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c96c0e7d16'
down_revision = '0d2d96b6f521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rental_zone_name_key', 'rental_zone', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rental_zone_name_key', 'rental_zone', type_='unique')
    # ### end Alembic commands ###
