"""model_no renamed to registration_no

Revision ID: fbad207f7e56
Revises: 99d25793e775
Create Date: 2021-11-28 09:28:50.064043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbad207f7e56'
down_revision = '99d25793e775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('registration_no', sa.String(), nullable=True))
    op.drop_constraint('car_model_no_key', 'car', type_='unique')
    op.create_unique_constraint('car_registration_no_key', 'car', ['registration_no'])
    op.drop_column('car', 'model_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('model_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('car_registration_no_key', 'car', type_='unique')
    op.create_unique_constraint('car_model_no_key', 'car', ['model_no'])
    op.drop_column('car', 'registration_no')
    # ### end Alembic commands ###
